# Generated by Django 4.0.2 on 2022-02-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titile',
            new_name='title',
        ),
    ]
